(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const y="Q8bHL81HES4CjxatVZAVSQWYyAffYhbQ",L=document.querySelector(".events-list"),r=document.getElementById("pagination");let l=0,c=0;async function d(a=0){var n,i;const s=`https://app.ticketmaster.com/discovery/v2/events.json?apikey=${y}&countryCode=US&size=20&page=${a}`,t=await(await fetch(s)).json(),e=((n=t._embedded)==null?void 0:n.events)||[];c=Math.min(((i=t.page)==null?void 0:i.totalPages)||0,29),l=a,b(e),E()}function b(a){const s=a.map(o=>{var p,u,m,f,g,h,v;const t=((u=(p=o.images)==null?void 0:p[0])==null?void 0:u.url)||"",e=o.name||"",n=((f=(m=o.dates)==null?void 0:m.start)==null?void 0:f.localDate)||"",i=((v=(h=(g=o._embedded)==null?void 0:g.venues)==null?void 0:h[0])==null?void 0:v.name)||"";return`
      <li class="event-card">
        <img class="event-img" src="${t}" alt="${e}">
        <h3 class="event-title" >${e}</h3>
        <p class="event-date">${n}</p>
        <p class="event-place">${i}</p>
      </li>
    `}).join("");L.innerHTML=s}function E(){r.innerHTML="";const a=5;let s=Math.max(0,l-2),o=Math.min(c,s+a);o-s<a&&(s=Math.max(0,o-a));for(let t=s;t<o;t++){const e=document.createElement("div");e.classList.add("page-btn"),t===l&&e.classList.add("active"),e.textContent=t+1,e.addEventListener("click",()=>{d(t)}),r.appendChild(e)}if(o<c){const t=document.createElement("div");t.textContent="...",t.style.padding="6px",t.style.color="#fff",r.appendChild(t);const e=document.createElement("div");e.classList.add("page-btn"),e.textContent=c,e.addEventListener("click",()=>{d(c-1)}),r.appendChild(e)}}d();
//# sourceMappingURL=commonHelpers.js.map
